### ISSUE TITLE
sound design

### ISSUE THREAD

**Issue by rachelwoodside** [shamone03/ludum-dare-53#12]
- siren
- collision noise
- pained grunt
- car/traffic ambience~!
- more detail: engine revving, etc.

**Comment by Strailxx** [comment]
Some files now in Audio folder, Theres everything I believe on the above list except for the grunt.

**Comment by Strailxx** [comment]
Caravan currently holds all grunting audio & car holds ambient audio, if merge conflicts occur not too difficult to take whoevers work and readd audio, Branch currently in a weird mid place with Tristans UI as it was the only way to get the health to work. **DO NOT** commit to main with this branch until UI is fully fleshed out and you are able to pull it onto this branch
